print("eres Cristian!!")
print("Te conozco mas de lo que crees")
print("Seguimos actualizando")
print("Hello git git git")
print("Nuevo texto")
print("texto 1")
print("holaaaa")
print("Se ha hecho lo que se tiene que hacer (git stash)")
print("CRISTIANOVIEDO12-HELLO-GIT")